# .tmuxinator.yml

name: mitchell-gravity-set
root: /development/cpp_proj/mitchell-gravity-set
on_project_first_start: loadxrdb
startup_window: mitchell-gravity-set

windows:
  - mitchell-gravity-set:
      layout: 3ccd,274x63,0,0{90x63,0,0,47,90x63,91,0,49,92x63,182,0[92x22,182,0,50,92x21,182,23,51,92x18,182,45,52]}
      panes:
        - coolprompt
        - note:
          - git status -sb
          - coolprompt
        - coolprompt
        - coolprompt
        - coolprompt
  - test:
      layout: 6597,272x98,0,0{89x98,0,0,149,89x98,90,0,161,92x98,180,0,162}
      panes:
        - cd compute ; coolprompt
        - cd gui ; coolprompt
        - cd build ; coolprompt

